### ISSUE TITLE
Student is unable to access category information (score, weight) 

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#202]
I couldn't find a way for a student to access the category data from the service?  It seems that the user needs `isUserAbleToViewAssignments(gradebookUid)`. Can this be made more permissive? Or is there another way we can get the student's category average and weight as a student user?

**Comment by steveswinsburg** [comment]
Hey @payten, the simplest way here is probably to just add the `CategoryDefinition` for the category into the `Assignment`, which I can add into the Assignment mapper in the GB service. It already adds a few of the fields, we can just add them all. But that would just be the settings info as per the fields in `CategoryDefinition`. Note that some fields from the category are already set into the `shared.Assignment`:

```
if(internalAssignment.getCategory() != null) {
            assignmentDefinition.setCategoryName(internalAssignment.getCategory().getName());
            assignmentDefinition.setWeight(internalAssignment.getCategory().getWeight());
            assignmentDefinition.setCategoryExtraCredit(internalAssignment.getCategory().isExtraCredit());
            assignmentDefinition.setCategoryId(internalAssignment.getCategory().getId());
        }
```

Or are you after the the calculated category score for the student, that takes into account all of the assignments for that category?

**Comment by payten** [comment]
Sounds good. And I believe we're after the calculated category score.  This is for use on the student's view of the gradebook and the "Student Review Mode" tab of the student grade summary popup.

**Comment by steveswinsburg** [comment]
Hmm, I'm not seeing anything in the service that should be stopping the categoryaverage from being returned for a student. What error are you seeing?

Also, the `StudentGradeSummaryGradesPanel` does a lot of manual work with the grades and figuring out categories, are we able to shift that back into the business service so the logic is all back there? WDYT?

**Comment by steveswinsburg** [comment]
Oh and for weight, if you have the Assignment, the getWeight is actually the category weight:
`assignmentDefinition.setWeight(internalAssignment.getCategory().getWeight());`

However Assignments inherit their weighting from the category so within a category they are all the same.

Had a chat with Kyle, in the student drill down, the only cell that will have the weight on it is the category. So is this one still an issue?

I can't see an issue with a call to get the category average either, but yeah send any error you get :)

**Comment by payten** [comment]
Ah great, pulling the weight from the assignment works a treat - thanks!

As a student, I'm having trouble getting the category average due to the permission error below.  From what I can see, the category average is calculated in `gradeInfo = buildGradeMatrix(...)` and then accessible via `gradeInfo.getCategoryAverages().get(myCategoryId)`. Perhaps all we need to do is move that calculation behaviour somewhere else? Or alternatively open up `getCategoryDefinitions` to students?

```
java.lang.SecurityException: You do not have permission to perform this operation
at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.getCategoryDefinitions(GradebookServiceHibernateImpl.java:2242)
at sun.reflect.GeneratedMethodAccessor486.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
at com.sun.proxy.$Proxy26.getCategoryDefinitions(Unknown Source)
at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.getGradebookCategories(GradebookNgBusinessService.java:292)
at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.getGradebookCategories(GradebookNgBusinessService.java:277)
at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.buildGradeMatrix(GradebookNgBusinessService.java:576)
```

**Comment by steveswinsburg** [comment]
Yep I think we could move that calculation around - I'll have a look at a way for students to get the category info. Possible issue is the Assignment list in the categorydefinition, but that could maybe be changed to be the AssignmentDefinition DTO instead of the full Assignment.

**Comment by steveswinsburg** [comment]
OK this is a bit tricky. The GradebookService has a few checks in there that are failing to run if a student. We are going to need a specific implementation for getting a categoryscore for a student.

**Comment by steveswinsburg** [comment]
See https://jira.sakaiproject.org/browse/SAK-29891

**Comment by steveswinsburg** [comment]
This is in progress, just need to test and adjust the methods.

**Comment by steveswinsburg** [comment]
PR here: https://github.com/sakaiproject/sakai/pull/1119
I have an associated business method to commit once this is in.

**Comment by steveswinsburg** [comment]
OK @payten this should be good to go now.

```
public Double getCategoryScoreForStudent(Long categoryId, String studentUuid, Map<Assignment,GbGradeInfo> grades);
```

**Comment by kyleblythe** [comment]
Since students can now access the category subtotal score/weight, I think this one's good to go?
