### ISSUE TITLE
Exception when accessing tool as a Teaching Assistant

### ISSUE THREAD

**Issue by payten** [steveswinsburg/gradebookNG#205]
It was raised on the call this week that the tool is throwing an exception for Teaching Assistants.

To replicate, I first added a TA and granted VIEW on a single category and all students.  When logged in as the TA, accessing the Gradebook got stuck at this point:

```
Time for [GradebookPage init] was: 0ms
Time for [getGradebookAssignments] was: 24ms
Time for [buildGradeMatrix].[buildGradeMatrix start] was: 0ms
Time for [buildGradeMatrix].[getGradebook] was: 4ms
2015-08-28 10:41:16,979  INFO http-nio-8080-exec-100 org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl - Returning no grade records for an empty collection of student UIDs
Time for [buildGradeMatrix].[getSiteCourseGrades] was: 39ms
Time for [buildGradeMatrix].[matrix seeded] was: 39ms
```

... still no reply after 5minutes and it seems to be stuck in `businessService.buildGradeMatrix`.

Changing the VIEW to GRADE, I hit a permission exception:

```
Time for [buildGradeMatrix].[getSiteCourseGrades] was: 21ms
Time for [buildGradeMatrix].[matrix seeded] was: 21ms
Time for [buildGradeMatrix].[getGradesForStudentsForItem: 25] was: 40ms
Time for [buildGradeMatrix].[updatedStudentGradeInfo: 25] was: 40ms
Time for [buildGradeMatrix].[getGradesForStudentsForItem: 26] was: 56ms
Time for [buildGradeMatrix].[updatedStudentGradeInfo: 26] was: 56ms
Time for [buildGradeMatrix].[getGradesForStudentsForItem: 27] was: 73ms
Time for [buildGradeMatrix].[updatedStudentGradeInfo: 27] was: 73ms
2015-08-28 10:36:28,512  WARN http-nio-8080-exec-98 RequestCycleExtra - ********************************
2015-08-28 10:36:28,512  WARN http-nio-8080-exec-98 RequestCycleExtra - Handling the following exception
org.apache.wicket.WicketRuntimeException: Can't instantiate page using constructor 'public org.sakaiproject.gradebookng.tool.pages.GradebookPage()'. An exception has been thrown during construction!
    at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:194)
    at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:67)
    at org.apache.wicket.DefaultMapperContext.newPageInstance(DefaultMapperContext.java:133)
    at org.apache.wicket.core.request.handler.PageProvider.resolvePageInstance(PageProvider.java:268)
    at org.apache.wicket.core.request.handler.PageProvider.getPageInstance(PageProvider.java:166)
    at org.apache.wicket.request.handler.render.PageRenderer.getPage(PageRenderer.java:78)
    at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:279)
    at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
    at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:862)
    at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
    at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:261)
    at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:218)
    at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:289)
    at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:259)
    at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:201)
    at org.apache.wicket.protocol.http.WicketServlet.doGet(WicketServlet.java:137)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:406)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
    at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:358)
    at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
    at org.sakaiproject.tool.impl.ActiveToolComponent$MyActiveTool.forward(ActiveToolComponent.java:513)
    at org.sakaiproject.portal.charon.SkinnableCharonPortal.forwardTool(SkinnableCharonPortal.java:1480)
    at org.sakaiproject.portal.charon.handlers.SiteHandler.doToolBuffer(SiteHandler.java:1171)
    at org.sakaiproject.portal.charon.handlers.SiteHandler.bufferContent(SiteHandler.java:1039)
    at org.sakaiproject.portal.charon.handlers.SiteHandler.doSite(SiteHandler.java:503)
    at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:275)
    at org.sakaiproject.portal.charon.handlers.SiteHandler.doGet(SiteHandler.java:156)
    at org.sakaiproject.portal.charon.SkinnableCharonPortal.doGet(SkinnableCharonPortal.java:837)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.sakaiproject.util.RequestFilter.doFilter(RequestFilter.java:467)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1517)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1474)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:175)
    ... 61 more
Caused by: java.lang.SecurityException: User 0ced46e5-fa3b-4db6-825c-e01590a25542 attempted to access grade information for student 6b9d911f-8d2b-490e-944c-e12f8cbb2839 without permission in gb test-site using gradebookService.getGradesForStudentsForItem
    at org.sakaiproject.component.gradebook.GradebookServiceHibernateImpl.getGradesForStudentsForItem(GradebookServiceHibernateImpl.java:1546)
    at sun.reflect.GeneratedMethodAccessor472.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy26.getGradesForStudentsForItem(Unknown Source)
    at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.buildGradeMatrix(GradebookNgBusinessService.java:599)
    at org.sakaiproject.gradebookng.business.GradebookNgBusinessService.buildGradeMatrix(GradebookNgBusinessService.java:515)
    at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$FastClassByCGLIB$$86be4ca5.invoke(<generated>)
    at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
    at org.apache.wicket.proxy.LazyInitProxyFactory$CGLibInterceptor.intercept(LazyInitProxyFactory.java:333)
    at WICKET_org.sakaiproject.gradebookng.business.GradebookNgBusinessService$$EnhancerByCGLIB$$23780ebe.buildGradeMatrix(<generated>)
    at org.sakaiproject.gradebookng.tool.pages.GradebookPage.<init>(GradebookPage.java:150)
```

**Comment by steveswinsburg** [comment]
The first one is interesting. Not sure why it got stuck? is that reproducible?
The second is probably still to do with how the permissions are applied to the list of users, which is annoying, but I can use this to dig into it. Thanks.

**Comment by payten** [comment]
Hm I'm able to replicate locally.  I have a course site, one student, one instructor, one TA and one grade item (no categories). The instructor gives the TA view access to all assignments and all students.  When trying to hit GradebookNG as the TA the requests never returns. Stepping through the code, I'm seeing an iterator loop forever (?):

```
 public class GradebookPermissionServiceImpl extends BaseHibernateManager implements GradebookPermissionService
      public Map<String, String> getStudentsForItem(Long gradebookId, String userId, List<String> studentIds, int cateType, Long categoryId, List courseSections)
      ...
          for(Iterator<String> studentIter = studentIds.iterator(); studentIter.hasNext();)
          {
              if(grade == true)
                  studentMap.put((String)studentIter.next(), GradebookService.gradePermission);
              else if(view == true)
                  studentMap.put((String)studentIter.next(), GradebookService.viewPermission);
          }
     ...
```

~~Does that seem plausible?~~ Aha, in my case, `grade == false` and `view == false` so  `iterator.next()` is never called.

**Comment by steveswinsburg** [comment]
OK I can reproduce also. On it.

**Comment by steveswinsburg** [comment]
Ok infinite loop issue should be fixed. Bug in permission service. Security Exception next.

**Comment by steveswinsburg** [comment]
Ok this should now be done. The issue was the new view_course_grade was setting null values for the category and groupId, however the permission check was getting the permissions for categories/groups where the values was null, in effect saying any category could be viewed. So this is now corrected and the permission checks are more explicit.

in addition, the list of categories visible for a TA are now compared against the category for each assignment when fetching grades in the matrix builder, and if the TA cannot access the category, no grades are fetched for that assignment.

Note that this requires two API mods:
https://jira.sakaiproject.org/browse/SAK-29866
https://jira.sakaiproject.org/browse/SAK-29867

**Comment by kyleblythe** [comment]
Will complete testing when #211 is in place.

**Comment by kyleblythe** [comment]
Confirmed.
